"""Local type stub: the MuPDF binding's exception base (not a RuntimeError), and glyph names."""

class FzErrorBase(Exception): ...
class FzFont: ...

# Glyph names (spec 13 section 3): a font's name for a glyph id, and the Adobe Glyph List's
# strict reading of a name (0 when the list does not map it).
def fz_get_glyph_name2(font: FzFont, glyph: int) -> str: ...
def fz_unicode_from_glyph_name_strict(name: str) -> int: ...
