class ConfigParser:
    def __init__(self, cli_options: dict[str, object]) -> None: ...
    def generate_config_dict(self) -> dict[str, object]: ...
    def get_processors(self) -> list[str] | None: ...
    def get_renderer(self) -> str: ...
