"""PDFium's C API as pypdfium2 5.13 binds it through ctypes: only the calls the verifier makes.

Handles are opaque pointers. An out-parameter is passed as the ctypes object itself: the bindings'
argtypes declare it as a pointer, so ctypes passes it by reference.
"""

import ctypes

class _Handle(ctypes._Pointer[ctypes.Structure]):
    # A pointer to one of PDFium's opaque structs; a NULL pointer is falsy.
    def __bool__(self) -> bool: ...

class FPDF_PAGE(_Handle): ...
class FPDF_TEXTPAGE(_Handle): ...
class FPDF_PAGEOBJECT(_Handle): ...
class FPDF_CLIPPATH(_Handle): ...
class FPDF_PATHSEGMENT(_Handle): ...

class FS_RECTF(ctypes.Structure):
    left: float
    top: float
    right: float
    bottom: float

class FS_MATRIX(ctypes.Structure):
    a: float
    b: float
    c: float
    d: float
    e: float
    f: float

FPDF_ERR_PASSWORD: int
FPDF_PAGEOBJ_TEXT: int
FPDF_PAGEOBJ_PATH: int
FPDF_PAGEOBJ_FORM: int
FPDF_SEGMENT_LINETO: int
FPDF_SEGMENT_BEZIERTO: int
FPDF_SEGMENT_MOVETO: int

def FPDF_GetPageBoundingBox(page: FPDF_PAGE, rect: FS_RECTF) -> int: ...
def FPDFPage_CountObjects(page: FPDF_PAGE) -> int: ...
def FPDFPage_GetObject(page: FPDF_PAGE, index: int) -> FPDF_PAGEOBJECT: ...
def FPDFFormObj_CountObjects(form_object: FPDF_PAGEOBJECT) -> int: ...
def FPDFFormObj_GetObject(form_object: FPDF_PAGEOBJECT, index: int) -> FPDF_PAGEOBJECT: ...
def FPDFPageObj_GetType(page_object: FPDF_PAGEOBJECT) -> int: ...
def FPDFPageObj_GetMatrix(page_object: FPDF_PAGEOBJECT, matrix: FS_MATRIX) -> int: ...
def FPDFPageObj_GetStrokeColor(
    page_object: FPDF_PAGEOBJECT,
    R: ctypes.c_uint,
    G: ctypes.c_uint,
    B: ctypes.c_uint,
    A: ctypes.c_uint,
) -> int: ...
def FPDFPageObj_GetFillColor(
    page_object: FPDF_PAGEOBJECT,
    R: ctypes.c_uint,
    G: ctypes.c_uint,
    B: ctypes.c_uint,
    A: ctypes.c_uint,
) -> int: ...
def FPDFPageObj_GetClipPath(page_object: FPDF_PAGEOBJECT) -> FPDF_CLIPPATH: ...
def FPDFClipPath_CountPaths(clip_path: FPDF_CLIPPATH) -> int: ...
def FPDFClipPath_CountPathSegments(clip_path: FPDF_CLIPPATH, path_index: int) -> int: ...
def FPDFClipPath_GetPathSegment(
    clip_path: FPDF_CLIPPATH, path_index: int, segment_index: int
) -> FPDF_PATHSEGMENT: ...
def FPDFPath_GetDrawMode(
    path: FPDF_PAGEOBJECT, fillmode: ctypes.c_int, stroke: ctypes.c_int
) -> int: ...
def FPDFPath_CountSegments(path: FPDF_PAGEOBJECT) -> int: ...
def FPDFPath_GetPathSegment(path: FPDF_PAGEOBJECT, index: int) -> FPDF_PATHSEGMENT: ...
def FPDFPathSegment_GetPoint(
    segment: FPDF_PATHSEGMENT, x: ctypes.c_float, y: ctypes.c_float
) -> int: ...
def FPDFPathSegment_GetType(segment: FPDF_PATHSEGMENT) -> int: ...
def FPDFPathSegment_GetClose(segment: FPDF_PATHSEGMENT) -> int: ...
def FPDFText_CountChars(text_page: FPDF_TEXTPAGE) -> int: ...
def FPDFText_GetUnicode(text_page: FPDF_TEXTPAGE, index: int) -> int: ...
def FPDFText_IsGenerated(text_page: FPDF_TEXTPAGE, index: int) -> int: ...
def FPDFText_IsHyphen(text_page: FPDF_TEXTPAGE, index: int) -> int: ...
def FPDFText_HasUnicodeMapError(text_page: FPDF_TEXTPAGE, index: int) -> int: ...
def FPDFText_GetLooseCharBox(text_page: FPDF_TEXTPAGE, index: int, rect: FS_RECTF) -> int: ...
def FPDFText_GetTextObject(text_page: FPDF_TEXTPAGE, index: int) -> FPDF_PAGEOBJECT: ...
