"""inkgrid: exact tables and text from born-digital PDFs.

`read()` turns a PDF into a validated `Document`; `read_pages()` returns the raw page model, for
debugging a reading.
"""

import importlib.metadata

from inkgrid.api import read, read_pages
from inkgrid.errors import (
    InkgridError,
    InvariantError,
    PasswordRequired,
    PdfOpenError,
    StrictModeError,
    WrongPassword,
)
from inkgrid.model import (
    Block,
    Cell,
    Defect,
    DefectCode,
    Definition,
    Document,
    Finding,
    FindingCode,
    Footnote,
    Furniture,
    Grid,
    Heading,
    Interval,
    Ledger,
    Lexicon,
    Link,
    LinkEnd,
    ListItem,
    PageCheck,
    PageInfo,
    PageModel,
    Paragraph,
    Producer,
    Profile,
    Reading,
    Rect,
    Region,
    Rule,
    Severity,
    Table,
    VerificationReport,
    Word,
)

__version__ = importlib.metadata.version("inkgrid")

__all__ = [
    "Block",
    "Cell",
    "Defect",
    "DefectCode",
    "Definition",
    "Document",
    "Finding",
    "FindingCode",
    "Footnote",
    "Furniture",
    "Grid",
    "Heading",
    "InkgridError",
    "Interval",
    "InvariantError",
    "Ledger",
    "Lexicon",
    "Link",
    "LinkEnd",
    "ListItem",
    "PageCheck",
    "PageInfo",
    "PageModel",
    "Paragraph",
    "PasswordRequired",
    "PdfOpenError",
    "Producer",
    "Profile",
    "Reading",
    "Rect",
    "Region",
    "Rule",
    "Severity",
    "StrictModeError",
    "Table",
    "VerificationReport",
    "Word",
    "WrongPassword",
    "__version__",
    "read",
    "read_pages",
]
